### ISSUE TITLE
UnmanagedLibrary = "turbojpeg"

### ISSUE THREAD

**Issue by 0shi** [georg-jung/MozJpegSharp#19]
Hi there,
I'm hoping this is a very silly question and I've missed something basic, but I was running through the code and spotted this: https://github.com/georg-jung/MozJpegSharp/blob/dfedace35de88b4c9773622e24cdb42ce6c57531/src/MozJpegSharp/TurboJpegImport.cs#L61

I was expecting this to be "mozjpeg" as opposed to the "turbojpeg" in [Quamotion.TurboJpegWrapper](https://github.com/quamotion/AS.TurboJpegWrapper/blob/f75490096267a4fc5a84f2701152085aea860f38/Quamotion.TurboJpegWrapper/TurboJpegImport.cs#L61).

I assume you're shipping the MozJpeg dll with nuget but just never renamed this in code / the nuget package generation steps?

**Comment by georg-jung** [comment]
Thanks for reading through the code and pointing this out! Mozjpeg is basically just a modified/improved version of libturbojpeg, which is why the wrappers can be so similar too. When introducing changes to turbojpeg, mozjpeg did not change the name of any binaries. It can be seen as a drop-in replacement for turbojpeg. That's why its correct that the code lists `turbojpeg` here - mozjpeg just _is_ (called) turbojpeg.

**Comment by 0shi** [comment]
Thanks for getting back so quickly and for your work!

I can see your approach in one of the other wrappers
https://github.com/JosePineiro/MozJpeg-wrapper/blob/7c074b9b7265879d1ead730f6e098bab039990cf/MozJpegTest/MozJpegWrapper.cs#L413

But I was thrown off by another wrapper using "mozjpeg" and making use of different methods
https://github.com/dmunch/mozjpeg.net/blob/d38cb9405a8206aa07c4fa2b4fc3770e9603a17d/mozjpeg.net.shared/StructsJpegLib.cs#L12

Cheers.

**Comment by georg-jung** [comment]
When starting this project I did this research too and got the feeling that each of the existing solutions had some shortcomings (i.e. beeing unmaintained for years, not following good practices regarding packaging, not including the native binaries etc). That's why I actually started this on my own. If you come to the conclusion that one of the other possibilities is better in specific points, feel free to open issues here - I'd be happy to look into that.

Meanwhile, I started working on a "V2" that is more cross platform (doesn't necessarily depend on GDI+/System.Drawing; split the native binaries in separate NuGet packages, a bit inspired by SqlitePclRaw). That's what you can currently see in master. It's not finished at this time though. I guess I did about 80% of the work yet but I don't have a to specific timeframe when in the next weeks I will finish working on it.

**Comment by 0shi** [comment]
Nothing to report so far - We're looking for a post-processor pretty naively, decided to evaluate MozJpeg and LibJpeg-Turbo wrappers rather than invoking the exes and ended up with your project and https://github.com/quamotion/AS.TurboJpegWrapper, mostly based on download numbers and contribution activity. I've tried dropping both in our project to do some performance / compression ratio testing and it's very gratifying that I can make use of either with only a change of imports, so really appreciate the closeness of the fork.

Personally, the speed of response from a maintainer is a super good sign as far as making that decision goes, thanks again for your hard work.
